### ISSUE TITLE
chocolatey package is currently a pre-release

### ISSUE THREAD

**Issue by nils-a** [CatenaLogic/RepositoryCleaner#99]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [X] .NET Standard
 - [ ] .NET Core

## Component

What component is this issue occurring in?

Installer

## Version of Library

1.0.0

## Version of OS(s) listed above with issue

Windows 10

## Steps to Reproduce
1. choco install repositorycleaner

## Expected Behavior
`RepositoryCleaner` is installed, as the Readme mentions

## Actual Behavior
```
❯ choco install repositorycleaner
Chocolatey v0.10.15
Installing the following packages:
repositorycleaner
By installing you accept licenses for the packages.
repositorycleaner not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
```

**Comment by GeertvanHorrik** [comment]
Good catch, thanks! We did release a stable version, but I think it has not yet been approved.
